### ISSUE TITLE
UpdateSetting not working

### ISSUE THREAD

**Issue by johnetherdice** [tronprotocol/tron-web#197]
Hi,

I am trying to change the user pay ratio for a contract that has already been deployed.

But it doesnt work

var update_setting =  async function() {
  var result = await tronWeb.transactionBuilder.updateSetting('contract address', 100);
  var signedtxn = await tronWeb.trx.sign(result, privateKey);
  var receipt = await tronWeb.trx.sendRawTransaction(signedtxn);
  console.log(result);
  console.log(receipt);
}

**Comment by sullof** [comment]
That should work. Can you provide more details, please?

**Comment by shenyongri110** [comment]
@johnetherdice I tried your example from my side, it's working properly. One thing you may take care is that in the updateSetting method, if you don't pass the ownerAddress, tronWeb will use the default account address when you initialized tronWeb. 
When you call sign method in the next step, the privateKey you pass should be same account of the contract owner, otherwise it will be failed.

Here is the signature of the updateSetting method, may help you.
updateSetting(contractAddress = false,
                  userFeePercentage = false,
                  ownerAddress = this.tronWeb.defaultAddress.hex,
                  callback = false)

**Comment by sullof** [comment]
@johnetherdice I am closing this issue. Feel free to re-open it if still have problems.
