### ISSUE TITLE
How do I sign rawTransaction with a private key

### ISSUE THREAD

**Issue by drunken005** [tronprotocol/tron-web#255]
eg:
rawTransaction: 0af7010a0295a02208da07aca55b506086408fa8e78e982d5ad301081f12ce010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e74726163741298010a154106f51c249260a777ae1b1ce47c61122278894fc6121541b436c687a8efe49163b8c6e15faaf8a94158d0c918a08d062264a80de0e8000000000000000000000000d7bfa8bfeb5822837878180a66921473339cf0d32e2f65863c22218b086445dc92b96a2692926987f7e1b2c5dcd72c0afea7c72400000000000000000000000000000000000000000000000000000000002217d57085b69afa972d9001a08d06

privateKey: af7c83e40cc67a355852b44051fc9e34452375ae569d5c18dd62e3859b9be229

Ether provides this method:
```js
const {Wallet: __wallet__, utils} = require("ethers");
let wallet = new __wallet__(privateKey);
let tx = utils.parseTransaction(rawTransaction);
wallet.sign(tx);
```

So what should TRON do?

**Comment by drunken005** [comment]
@sullof cc

**Comment by sullof** [comment]
You cannot sign a raw transaction because TronWeb does not have any method to parse a raw transaction. The reason for that is that to decode it correctly TronWeb should access the protobuf via gRPC, but TronWeb can communicate only with HTTP resources.
We think of building in the future a version of TronWeb able to talk gRPC, but for now there is nothing like that.
