### ISSUE TITLE
am I  overparanoid during trx.sendTransaction?

### ISSUE THREAD

**Issue by SiestaMadokaist** [tronprotocol/tron-web#41]
looking at: 
line 541: https://github.com/tronprotocol/tron-web/blob/master/src/lib/trx.js

        try {
            const address = options.privateKey ? this.tronWeb.address.fromPrivateKey(options.privateKey) : options.address;
            const transaction = await this.tronWeb.transactionBuilder.sendTrx(to, amount, address);
            const signedTransaction = await this.sign(transaction, options.privateKey || undefined);
            const result = await this.sendRawTransaction(signedTransaction);

            return callback(null, result);
        } catch(ex) {
            return callback(ex);
        }

since we're asking a remote server to create our transaction, isn't it possible that the response will contain a fraud transaction

e.g: 
we requested: 

       { 
            to_address: '41c65c9d73eee1f3059af3de7a1910d35b0b3ec166', 
            owner_address: '41e9cad8e4ca369ab272a76ee7299f520c41747aba',
            amount: 1 
        }

but then server's response:

        {
              txID: ...
              rawData: {
                      owner_address: '41bef6dc4af18c9d532137ff4bc457eff72f8c39f6',
                      to_address:  '41c65c9d73eee1f3059af3de7a1910d35b0b3ec166'
                     // instead of: 41e9cad8e4ca369ab272a76ee7299f520c41747aba,
                      amount: 1000
              }
       }

and then we still sign it and broadcast it anyway...

also, in an unrelated note, is it make sense to return the txid in the `sendTransaction` method?

**Comment by imediabiz** [comment]
Its okey. Thats fine I think

**Comment by kookiekrak** [comment]
It's definitely valid. TronLink will actually intercept the call to create the transaction and manually do it themselves in the chrome wallet to prevent this kind of attack.

The function is available because many people will use tronweb on a server with a locally hosted node, where these security concerns arent an issue.

You can use .transactionbuilder to create the transaction, then validate the contents before signing and broadcasting as an alterative too.

**Comment by kookiekrak** [comment]
gonna close. let me know if you have any other concerns
